dubbo:
  application:
    name: accountService
spring:
  datasource:
    druid:
      db-type: mysql
jdbc:
  driver: com.mysql.dj.jdbc.Driver
  url: jdbc:mysql:/124.221.168.200/ifx-develop?useUnicode=true&characterEncoding=utf-8&txcAppName=account
  username: ifx
  password: ifx2022in

