spring:

  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_HOST: localhost:8848}
#    config:
#      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
#          uri: lb://account-service
          uri: ${account-service-url:http://localhost:8001}
          predicates:
            - Path=/api/account/**
        - id: session-service
          uri: lb://session-service
            - Path=/api/session/**
          predicates:
            - Path=/api/session/**
  config:
    activate:
      on-cloud-platform:
server:
  port: 8761

alibaba:
  nacos:
    discovery:
      server-addr: ${nacos.discovery.server-addr} # Nacos注册中心地址
      namespace: ${nacos.discovery.namespace:} # Nacos命名空间
#  data:
#    mongodb:
#      host: 124.221.168.200
#      port: 27017
#      username: admin
#      password: admin
#      database: ifx
#  datasource:
    #    driver-class-name: com.alibaba.druid.proxy.DruidDriver
#    druid:
#      username: ifx
#      password: ifx2022
#      url: jdbc:mysql://124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=formService
#      driver-class-name: com.mysql.jdbc.Driver
#jdbc:
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql:/124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=gateway
#  username: root
#  password: root
