
dubbo:
  application:
    name: accountService
    dump-directory: /data/dump
  consumer:
    check: false
  registry:
    address: nacos://124.221.168.200:8848?username=ifx2022?password=ifx2022?namespce=ccfffa41-d050-42eb-b29b-037ac8b43fc9
    password: ifx2022
    username: ifx2022
  protocol:
    port: 20891
    name: dubbo

spring:
  data:
    mongodb:
      host: 124.221.168.200
      port: 27017
      username: admin
      password: admin
      database: ifx
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: ifx
      password: ifx2022
      url: jdbc:mysql://124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=account&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ifx-server
