dubbo:
  registry:
    address: nacos://124.221.168.200:8848
    username: ifx2022
    password: ifx2022
  application:
    id: ifx-gateway
    name: ifx-gateway

spring:
  data:
    mongodb:
      host: 124.221.168.200
      port: 27017
      username: admin
      password: admin
      database: ifx
  datasource:
    #    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    druid:
      username: ifx
      password: ifx2022
      url: jdbc:mysql://124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=formService
      driver-class-name: com.mysql.jdbc.Driver
#jdbc:
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql:/124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=gateway
#  username: root
#  password: root
