server:
  port: ${SERVICE_PORT:8001}
spring:
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER_NAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
  application:
    name: ${APP-NAME:account-service}
  r2dbc:
    host: ${MYSQL_HOST:124.221.168.200}
    port: ${MYSQL_PORT:3306}
#    url: r2dbc:mysql://${MYSQL_HOST:124.221.168.200}:${MYSQL_PORT:3306}/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=${APP_NAME:account}&useSSL=true
    username: ifx
    password: ifx2022
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 10m
      validation-query: SELECT 1
