eureka:
  instance:
    hostname: account-service
    appname: account-service
    healthCheckUrlPath: ${server.servletPath}/health
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001
spring:
  application:
    name: account
  r2dbc:
    url: r2dbc:mysql://124.221.168.200:3306/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=account&useSSL=true
    username: ifx
    password: ifx2022
    pool:
      initial-size: 100
      max-size: 200
      max-idle-time: 30m
      validation-query: SELECT 1
  data:
    mongodb:
      host: 124.221.168.200
      port: 27017
      username: admin
      password: admin
      database: ifx
