
#dubbo:
#  application:
#    name: accountService
#    dump-directory: /data/dump
#  consumer:
#    check: false
#  registry:
#    address: nacos://124.221.168.200:8848?username=ifx2022?password=ifx2022?namespce=ccfffa41-d050-42eb-b29b-037ac8b43fc9
#    password: ifx2022
#    username: ifx2022
#  protocol:
#    port: 20891
#    name: dubbo
eureka:
  instance:
    hostname: account-service
    appname: account-service
    healthCheckUrlPath: ${server.servletPath}/health
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001
spring:
  application:
    name: account
#  security:
#    oauth2:
#      client:
#        registration:
#          google-login:
#            provider: google
#          google:
#            client-id: google-client-id
#            client-secret: google-client-secret
  r2dbc:
    url: r2dbc:mysql://124.221.168.200:3306/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=account&useSSL=true
    username: ifx
    password: ifx2022
    pool:
#      enabled: true
      initial-size: 100
      max-size: 200
      max-idle-time: 30m
      validation-query: SELECT 1
  data:
    mongodb:
      host: 124.221.168.200
      port: 27017
      username: admin
      password: admin
      database: ifx
#  datasource:
#    druid:
#      username: ifx
#      password: ifx2022
#      url: jdbc:mysql://124.221.168.200/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=account&useSSL=true
#      driver-class-name: com.mysql.cj.jdbc.Driver
