server:
  port: ${SERVICE_PORT:8001}

spring:

  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER_NAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
  application:
    name: ${APP-NAME:account-service}
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:3306/ifx?useUnicode=true&characterEncoding=utf-8&txcAppName=${spring.application.name:account-service}&useSSL=true
    username: ${MYSQL_USERNAME:ifx}
    password: ${MYSQL_PASSWORD:ifx2022}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 10m
      validation-query: SELECT 1
logging:
  level:
    org:
      springframework:
        r2dbc: TRACE
